In [1]:
import numpy as np
from pyDatalog import pyDatalog
from pyDatalog import pyEngine

In [2]:
def Product(x, y):
    z = []
    for x1 in x:
        for y1 in y.T:
            z.append(max(np.multiply(x1, y1)))
    return np.array(z).reshape((x.shape[0], y.shape[1]))

In [5]:
kl = np.array([[0, 0.2, 0.7, 0.8], [0, 0.3, 0.7, 0.5], [0.5, 0.5, 0.5, 0.5], [0.7, 0.4, 0.4, 0.6], [0.7, 0.7, 0.3, 0.3]])
vl = np.array([[0, 0.3, 0.3, 0.7, 0], [0.3, 0.1, 0.7, 0.3, 0.8], [0.8, 0.6, 0.5, 0.4, 0.3], [0.8, 0.8, 0.5, 0.6, 0.2]])
print(kl)
print(vl)

[[ 0.   0.2  0.7  0.8]
 [ 0.   0.3  0.7  0.5]
 [ 0.5  0.5  0.5  0.5]
 [ 0.7  0.4  0.4  0.6]
 [ 0.7  0.7  0.3  0.3]]
[[ 0.   0.3  0.3  0.7  0. ]
 [ 0.3  0.1  0.7  0.3  0.8]
 [ 0.8  0.6  0.5  0.4  0.3]
 [ 0.8  0.8  0.5  0.6  0.2]]


In [6]:

print(Product(kl, vl))

[[ 0.64  0.64  0.4   0.48  0.21]
 [ 0.56  0.42  0.35  0.3   0.24]
 [ 0.4   0.4   0.35  0.35  0.4 ]
 [ 0.48  0.48  0.3   0.49  0.32]
 [ 0.24  0.24  0.49  0.49  0.56]]
